# Generated by Django 4.0.3 on 2022-04-07 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0002_dish_topping_delete_dishtopping'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id'], 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='sizetype',
            options={'ordering': ['id']},
        ),
    ]
