# Generated by Django 4.0.3 on 2022-04-07 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Принят на обработку'), (2, 'Готовится'), (3, ' Готово'), (4, 'Получено клиентом')], default=1),
            preserve_default=False,
        ),
    ]
